name: Duels
main: com.meteordevelopments.duels.DuelsPlugin
version: @VERSION@
softdepend: [ AxGraves, BountyHunters, CombatLogX, CombatTagPlus, DeluxeCombat, Essentials, Factions, LeaderHeads, mcMMO, MVdWPlaceholderAPI, MyPet, PlaceholderAPI, NotBounties, PvPManager, SimpleClans, Vault, WorldGuard, Multiverse-Core, My_Worlds, MultiWorld ]
# Multiverse-Core added as soft-depend due to locations being null when Duels is loaded first.
# Add any world management plugins to softdepend list if arena doesn't load properly in the generated world.
api-version: 1.13

author: Realized, DUMBO
website: https://www.spigotmc.org/resources/duelsoptimised.118881/
description: An ultimate solution to server owners wanting to create a duel system.

commands:
  duel:
    description: Send, accept, or deny a duel request.
    aliases: [ 1v1 ]
  party:
    description: Create, join, and duel parties.
    aliases: [ p, duelparty, dp ]
  queue:
    description: Join or leave a queue.
    aliases: [ q ]
  spectate:
    description: Spectate a duel.
    aliases: [ spec ]
  duels:
    description: Administrative command of Duels.
    aliases: [ ds ]
  kit:

permissions:
  duels.*:
    children:
      duels.admin: true
  duels.admin:
    children:
      duels.default: true
      duels.stats.others: true
      duels.kits.*: true
      duels.teleport.bypass: true
      duels.spectate: true
      duels.spectate.anonymously: true
      duels.use.*: true
      duels.queue: true
  duels.default:
    children:
      duels.duel: true
      duels.stats: true
      duels.toggle: true
      duels.top: true
  duels.duel:
    default: true

folia-supported: true